# 必要数据及设置
bot_qq: 2289266990
host_qq: 1395790870
mirai_host: http://localhost:23456
verify_key: 762094
db_link: sqlite+aiosqlite:///sqlite.db
web_manager_api: true
web_manager_auto_boot: true
proxy: proxy

# 路径相关
image_path:
  setu: /home/yutou/sagiri/sagiri-bot/image/setu
  setu18: /home/yutou/sagiri/sagiri-bot/image/setu18
  real: /home/yutou/sagiri/sagiri-bot/image/real
  real_highq: /home/yutou/sagiri/sagiri-bot/image/real_highq
  bizhi: /home/yutou/sagiri/sagiri-bot/image/bizhi
  sketch: /home/yutou/sagiri/sagiri-bot/image/sketch

# 功能相关
functions:
  tencent:
    secret_id: AKIDoTvBE2cz95mFTTEk01nLfkbEeqpdDYhc
    secret_key: jDSSCgurY0D8l8LL6eFckcGeohKhoeFd
  saucenao_api_key:  85f4f8237c77a5ac6099c2347bca5fecc1e8be1f
  wolfram_alpha_key: 3WKRTT-J5QRE9Q4TK
  shadiao_app_name: shadiao_app_name
  github:
    username: Moore2253
    token: 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
  pica:
    username: username
    password: password
    download_cache: true
    search_cache: true
    daily_download_limit: 1
    daily_search_limit: 1
    daily_random_limit: 1
    daily_rank_limit: 1
    compress_password: i_luv_sagiri
  bilibili:
    cookie: cookie

# 日志相关
log_related:
  error_retention: 14
  common_retention: 7

# 数据相关
data_related:
  lolicon_image_cache: true
  lolicon_data_cache: true
  network_data_cache: true
  automatic_update: false
  data_retention: true

# 数据库相关
database_related:
  mysql:
    disable_pooling: false
    pool_size: 40
    max_overflow: 60