"""update

Revision ID: 01103dd37fa2
Revises: dab513fd1193
Create Date: 2022-05-25 12:24:53.832606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01103dd37fa2'
down_revision = 'dab513fd1193'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
