"""update

Revision ID: 03c0d3f2077a
Revises: 01103dd37fa2
Create Date: 2022-05-25 13:43:26.072151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03c0d3f2077a'
down_revision = '01103dd37fa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
