"""update

Revision ID: 1f5766fef5ae
Revises: f3a4855225ab
Create Date: 2022-06-06 18:09:09.882388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f5766fef5ae'
down_revision = 'f3a4855225ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
