"""update

Revision ID: 5f1314b7db40
Revises: 6b7f1bfc0e99
Create Date: 2022-05-25 10:41:38.695626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f1314b7db40'
down_revision = '6b7f1bfc0e99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
