"""update

Revision ID: 60abb80c1437
Revises: 03c0d3f2077a
Create Date: 2022-05-25 14:30:43.598522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60abb80c1437'
down_revision = '03c0d3f2077a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
