"""update

Revision ID: 801ea6e8e43d
Revises: c45e744b29c2
Create Date: 2022-06-02 09:47:30.880482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '801ea6e8e43d'
down_revision = 'c45e744b29c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
