"""update

Revision ID: 9c3f5acc45f0
Revises: c4b8c7f8f35b
Create Date: 2022-05-25 18:39:54.240126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c3f5acc45f0'
down_revision = 'c4b8c7f8f35b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
