"""update

Revision ID: b9f89c08a82b
Revises: 9c3f5acc45f0
Create Date: 2022-05-26 17:41:38.928309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9f89c08a82b'
down_revision = '9c3f5acc45f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
