"""update

Revision ID: c45e744b29c2
Revises: b9f89c08a82b
Create Date: 2022-05-31 15:26:44.896700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c45e744b29c2'
down_revision = 'b9f89c08a82b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
