"""update

Revision ID: c4b8c7f8f35b
Revises: 60abb80c1437
Create Date: 2022-05-25 17:10:14.660167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4b8c7f8f35b'
down_revision = '60abb80c1437'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
