"""update

Revision ID: dab513fd1193
Revises: e5d1fab3e78d
Create Date: 2022-05-25 11:03:52.414621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dab513fd1193'
down_revision = 'e5d1fab3e78d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
