"""update

Revision ID: e5d1fab3e78d
Revises: 5f1314b7db40
Create Date: 2022-05-25 11:00:00.303727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5d1fab3e78d'
down_revision = '5f1314b7db40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
