"""update

Revision ID: e74af1387946
Revises: 801ea6e8e43d
Create Date: 2022-06-05 15:56:35.141264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e74af1387946'
down_revision = '801ea6e8e43d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
