"""update

Revision ID: f3a4855225ab
Revises: 8cd3f5c58898
Create Date: 2022-06-05 22:29:00.323938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3a4855225ab'
down_revision = '8cd3f5c58898'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
